AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aus-weather-archive

  Sample SAM Template for aus-weather-archive

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  BOMDownloadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: aus_weather_archive/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 180
      Environment:
        Variables:
          PARAM1: "VALUE"
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Name: myScheduledEvent
      Policies:
        - S3ReadPolicy:
            BucketName: "radar-frames-829280336906"
        - S3WritePolicy:
            BucketName: "radar-frames-829280336906"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BOMDownloadFunction:
    Description: BOM download Lambda Function ARN
    Value: !GetAtt BOMDownloadFunction.Arn
  BOMDownloadFunctionIamRole:
    Description: Implicit IAM Role created for BOM download function
    Value: !GetAtt BOMDownloadFunctionRole.Arn
